import pathlib


# Controller class manages the interactions between the model and view class
class Controller:
    def __init__(self, model, view):
        self.model = model
        self.view = view
        self.raw_audio = "Clap.wav"

    # Takes the canvas generated by the model class and displays it in views tkinter window
    def display_plot_in_tkinter(self):
        canvas_widget = self.model.plot_waveform(self.view)
        # Add the Matplotlib canvas to the Tkinter window
        canvas_widget.grid(row=4, column=1, sticky='w')

    # Takes the rt60 graph generated in model and displays it within views tkinter window
    def display_rt_in_tkinter(self, freq_range):
        time, controller_widget = self.model.get_rd60_display(self.view, freq_range)
        self.view.reverb_label['text'] = f'Reverb: {time} seconds'
        self.view.canvas1 = controller_widget
        self.view.canvas1.grid(row=4, column=4, columnspan=5, sticky='w')

    # Takes the spectrogram generated in model and displays it within the tkinter window from view
    def display_spectogram_in_tkinter(self):
        self.view.reverb_label['text'] = ''
        self.view.canvas1 = self.model.plot_spectogram(self.view)
        self.view.canvas1.grid(row=4, column=4, columnspan=5, sticky='w')

    # Loads data validated by the model class and uses it to update the tkinter window in view
    def load_data(self):
        file = pathlib.Path(self.model.load()).name
        if file != '':
            self.view.name_label['text'] = f'Name: {file}'
            self.view.time_label['text'] = f'Time: {self.model.get_length(self.raw_audio)}'
            self.view.frequency_label['text'] = f'Frequency: {self.model.get_frequency()}'
            self.display_plot_in_tkinter()
            self.view.loaded = True

    # displays a combination of all rt60s plotted to a canvas generated by model and displays it along with the 0.5 difference of the average rt60
    def display_all_rt_in_tkinter(self):
        time_h, controller_widget_h = self.model.get__all_rd60_display(self.view)

        self.view.reverb_label['text'] = f'Difference: {time_h - 0.5} seconds'
        self.view.canvas1 = controller_widget_h
        self.view.canvas1.grid(row=4, column=4, columnspan=5, sticky='w')

